In [1]:
import torch

In [1]:
import torch

# ------------------------------------
# Scalar (0-D)
# ------------------------------------

a = torch.tensor(5)

print("Scalar")
print(a)
print(a.shape)

# ------------------------------------
# Vector (1-D)
# ------------------------------------

b = torch.tensor([1,2,3,4])

print("\nVector")
print(b)
print(b.shape)

# ------------------------------------
# Matrix (2-D)
# ------------------------------------

c = torch.tensor([
    [1,2,3],
    [4,5,6]
])

print("\nMatrix")
print(c)
print(c.shape)

# ------------------------------------
# 3-D Tensor
# ------------------------------------

d = torch.tensor([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])

print("\n3-D Tensor")
print(d)
print(d.shape)

Scalar
tensor(5)
torch.Size([])

Vector
tensor([1, 2, 3, 4])
torch.Size([4])

Matrix
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])

3-D Tensor
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])


In [5]:
print(c[0])
print(c[1])
print(c[0][2])
print(d.shape)

tensor([1, 2, 3])
tensor([4, 5, 6])
tensor(3)
torch.Size([2, 2, 2])


In [ ]:
import torch

a = torch.tensor([1,2,3])

b = torch.tensor([4,5,6])

print("a =", a)
print("b =", b)

print("\nAddition")
print(a + b)

print("\nSubtraction")
print(a - b)

print("\nMultiplication")
print(a * b)      # element-wise

print("\nDivision")
print(a / b)

a = tensor([1, 2, 3])
b = tensor([4, 5, 6])

Addition
tensor([5, 7, 9])

Subtraction
tensor([-3, -3, -3])

Multiplication
tensor([ 4, 10, 18])

Division
tensor([0.2500, 0.4000, 0.5000])


In [7]:
A = torch.tensor([
    [1,2],
    [3,4]
])

B = torch.tensor([
    [5,6],
    [7,8]
])
A @ B # matrix multiplication

tensor([[19, 22],
        [43, 50]])

In [8]:
x = torch.tensor([
    [10,20,30],
    [40,50,60]
])
print(x.shape)
print(x[1][2])
print(x[:,1])
print(x[0,:])

torch.Size([2, 3])
tensor(60)
tensor([20, 50])
tensor([10, 20, 30])


In [10]:
import torch

print("Torch Version :", torch.__version__)
print("Torch CUDA Version :", torch.version.cuda)
print("CUDA Available :", torch.cuda.is_available())
print("Device Count :", torch.cuda.device_count())

Torch Version : 2.12.1+cpu
Torch CUDA Version : None
CUDA Available : False
Device Count : 0


In [1]:
import torch

print("Torch Version :", torch.__version__)
print("Torch CUDA Version :", torch.version.cuda)
print("CUDA Available :", torch.cuda.is_available())
print("Device Count :", torch.cuda.device_count())

if torch.cuda.is_available():
    print("GPU :", torch.cuda.get_device_name(0))

Torch Version : 2.11.0+cu128
Torch CUDA Version : 12.8
CUDA Available : True
Device Count : 1
GPU : NVIDIA GeForce RTX 3050 4GB Laptop GPU


In [2]:
import sys
import torch

print(sys.executable)
print(torch.__version__)
print(torch.__file__)

c:\Users\shiva\anaconda3\envs\chirag_ai\python.exe
2.11.0+cu128
c:\Users\shiva\anaconda3\envs\chirag_ai\lib\site-packages\torch\__init__.py


In [3]:
import torch
import time

device = torch.device("cuda")

x = torch.randn(10000, 10000).to(device)
y = torch.randn(10000, 10000).to(device)

torch.cuda.synchronize()

start = time.time()

z = torch.matmul(x, y)

torch.cuda.synchronize()

print("Time:", time.time() - start)
print("Device:", z.device)

Time: 0.8638720512390137
Device: cuda:0


In [2]:
import json

with open("data/splits.json", "r") as f:
    splits = json.load(f)

train = set(splits["train"])
val = set(splits["validation"])
test = set(splits["test"])

print("Train size:", len(train))
print("Validation size:", len(val))
print("Test size:", len(test))

print("Train ∩ Validation:", train & val)
print("Train ∩ Test:", train & test)
print("Validation ∩ Test:", val & test)

Train size: 921
Validation size: 307
Test size: 308
Train ∩ Validation: set()
Train ∩ Test: set()
Validation ∩ Test: set()
